export default {
  ADD_MUSIC: "ADD_MUSIC",
  DELETE_MUSIC: "DELETE_MUSIC",
  UPDATE_MUSIC: "UPDATE_MUSIC",

  SET_INPUT_TITLE: "SET_INPUT_TITLE",
  SET_INPUT_CONTENT: "SET_INPUT_CONTENT",
  SET_INPUT_ID: "SET_INPUT_ID",
  RESET_INPUT: "RESET_INPUT",
};
